# Dependencies
markdown: kramdown
highlighter: rouge
redcarpet:
  extensions:
    [
      "no_intra_emphasis",
      "tables",
      "autolink",
      "strikethrough",
      "with_toc_data",
    ]

# Permalinks
# permalink: /:year-:month-:day-:title/
permalink: pretty
future: true
# relative_permalinks: true

# Setup
title: VagrantPi Blog
tagline: "JavaScript, Front-End, Back-End, Full Stack, Linux, 筆記, 生活札記"
description: "生活札記，記錄些學習筆記和生活"
baseurl: /

site:
  url: https://vagrantpi.github.io

author:
  name: VagrantPi
  url: https://vagrantpi.github.io/about/

paginate: 8

# Custom vars
version: 2.1.0

twitter:
  username: VagrantPi

github:
  repo: https://github.com/poole/hyde
  logo: https://vagrantpi.github.io/public/favicon.ico

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-twitter-plugin

social:
  links:
    - https://github.com/VagrantPi
    - https://twitter.com/VagrantPi
    - https://www.facebook.com/VagrantPi

# SEO
jekyll-seo-tag:
  default:
    name: "VagrantPi Blog"
    locale: "zh-TW"
    author:
      name: VagrantPi
      url: https://vagrantpi.github.io/about/
    description: "生活札記，記錄些學習筆記和生活"
    image: "https://vagrantpi.github.io/public/apple-touch-icon-144-precomposed.png"